name: 'ZC Embeddable View Paragraph'
description: 'Installs Zoocha Embeddable View Paragraph Component'
type: 'Feature'

recipes:
  - zr-paragraph-bundle
install:
  - viewsreference
config:
  strict: false
